### ISSUE TITLE
Unable to install on mac - ImportError: No module named pyside2uic - Python 3?

### ISSUE THREAD

**Issue by andytriboletti** [dreamworksanimation/usdmanager#16]
andytriboletti@andys-mbp ~ % usdmanager        
Traceback (most recent call last):
  File "/usr/local/bin/usdmanager", line 4, in <module>
    __import__('pkg_resources').run_script('usdmanager==0.9.0', 'usdmanager')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/usdmanager-0.9.0-py2.7.egg/EGG-INFO/scripts/usdmanager", line 17, in <module>
    from usdmanager import run
  File "/usr/local/lib/python2.7/site-packages/usdmanager-0.9.0-py2.7.egg/usdmanager/__init__.py", line 74, in <module>
    from . import highlighter, images_rc, utils
  File "/usr/local/lib/python2.7/site-packages/usdmanager-0.9.0-py2.7.egg/usdmanager/highlighter.py", line 26, in <module>
    from .utils import findModules
  File "/usr/local/lib/python2.7/site-packages/usdmanager-0.9.0-py2.7.egg/usdmanager/utils.py", line 34, in <module>
    import pyside2uic as uic
ImportError: No module named pyside2uic

I tried installing macports, and Pyside, Pyside2, etc. Already had and tried brew.

**Comment by mds-dwa** [comment]
Can you confirm if you have python 2 or python 3 running on your Mac? Based on the title, I'm guessing python 3?

**Comment by andytriboletti** [comment]
I have both.

andytriboletti@andys-mbp ~ % python --version
Python 2.7.17
andytriboletti@andys-mbp ~ % python3 --version
Python 3.7.6

**Comment by mds-dwa** [comment]
I never managed to get a python2 version running on my personal Mac due to Qt requirements. There is an outdated, unofficial (but still very usable!) python3 branch available here if you want to give it a try: https://github.com/mdsandell/usdmanager/tree/python3

I'll see if we can get any traction on an official python3 branch here, since I think that'll do the trick for you. PRs are always welcome if you do find a solution.

The only other thing I'd check is that your python path properly includes the PySide2 installation. Running "python" and trying that "import pyside2uic" line from a terminal should do the trick. If that doesn't work, but "import PySide2" does work, you may need to download pyside2uic separately from some place like https://github.com/pyside/pyside2-tools.

**Comment by mds-dwa** [comment]
There's now an official [python3 branch](https://github.com/dreamworksanimation/usdmanager/tree/python3) available. I'd recommend giving this a try.
