### ISSUE TITLE
I have trouble in launching usdmanger caused by pyside2uic

### ISSUE THREAD

**Issue by 0k1019** [dreamworksanimation/usdmanager#20]
Hello, I am ARKit engineer with usd file format.
I try to use usdmanager the purpose of project is really good.
So, I installed Qt and pyside2 in python 2.7, mac os  env.
I saw error about pyside2uic error. 
How can I install pyside2uic?

I saw issue about pyside2uic, it doesn't help my problem.

```
Traceback (most recent call last):
  File "/Users/younghokwon/usdmanager/venv/bin/usdmanager", line 4, in <module>
    __import__('pkg_resources').run_script('usdmanager==0.10.0', 'usdmanager')
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/usdmanager-0.10.0-py2.7.egg/EGG-INFO/scripts/usdmanager", line 17, in <module>
    from usdmanager import run
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/usdmanager-0.10.0-py2.7.egg/usdmanager/__init__.py", line 74, in <module>
    from . import highlighter, images_rc, utils
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/usdmanager-0.10.0-py2.7.egg/usdmanager/highlighter.py", line 26, in <module>
    from .utils import findModules
  File "/Users/younghokwon/usdmanager/venv/lib/python2.7/site-packages/usdmanager-0.10.0-py2.7.egg/usdmanager/utils.py", line 34, in <module>
    import pyside2uic as uic
ImportError: No module named pyside2uic
```

**Comment by mds-dwa** [comment]
Hello!

This same problem for Mac was reported in
https://github.com/dreamworksanimation/usdmanager/issues/16. My comment
here --
https://github.com/dreamworksanimation/usdmanager/issues/16#issuecomment-594147543
-- has some suggestions that you could try, and includes a link to where
pyside2uic can be manually downloaded if it isn't already on your system.
Good luck!

Sincerely,

Mark S.

**Comment by 0k1019** [comment]
Thanks for reply. I change OS to ubuntu 16.04 and install whole process.

**Comment by mds-dwa** [comment]
Awesome, I’m glad it worked out!
