### ISSUE TITLE
Trouble installing on windows

### ISSUE THREAD

**Issue by ollied-xx** [dreamworksanimation/usdmanager#21]
Hi there,

I am trying to run through getting usdmanager up and running on windows 10.  I have gone through the steps here.
https://github.com/dreamworksanimation/usdmanager/blob/master/docs/installation.md#windows

All seemed to go well to the last point of launching the app (step 7), ie no errors on setup etc.  When I try and run the command, I get the following error.

`E:\gitHub\usdmanager\usdmanager>python C:\Python27\Scripts\usdmanager
Traceback (most recent call last):
  File "C:\Python27\Scripts\usdmanager", line 4, in <module>
    __import__('pkg_resources').run_script('usdmanager==0.10.0', 'usdmanager')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1453, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/usdmanager' not found in metadata at 'e:\\github\\usdmanager\\usdmanager\\usdmanager.egg-info'
`

As a side note, I have USD 20.05 installed and working.

**Comment by Ryan-Roberts-Unity** [comment]
Try running usdmanager from within your Python's script directory. 

I too see this error (Win11 with Python 3.7.4) when trying to run it in a directory outside of the Python environment.
```
c:\bin\usdmanager-0.15.0>python c:\Python374\Scripts\usdmanager
Traceback (most recent call last):
  File "c:\Python374\Scripts\usdmanager", line 4, in <module>
    __import__('pkg_resources').run_script('usdmanager==0.15.0', 'usdmanager')
  File "c:\python374\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "c:\python374\lib\site-packages\pkg_resources\__init__.py", line 1437, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/usdmanager' not found in metadata at 'c:\\bin\\usdmanager-0.15.0\\usdmanager.egg-info'
```

The forward slash seen in "scripts/usdmanager" is notable as Windows uses backslashes so my guess is there's a pathing bug somewhere.
